### ISSUE TITLE
Ability to see all activity logged against a contact via a timeline view.

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-contacts#13]
As a B2C company, I’d like the ability to see all activity logged against a contact via a timeline view.  I’d like the ability to filter this view based on:

- Communications
- Opportunities created
- Updates to attributes
- Date
-

**Comment by avalot** [comment]
This activity log needs to be part of the contact's chronology (a.k.a. "conversations history"). 

UX rule: Only one chronology.

**Comment by Kasia9090** [comment]
@avalot @mattbr0wn is activity log the same as "conversations history"? Should naming be changed to be less confusing and accomodate wider set of "activities"?

@mattbr0wn do we have right now data for "created opportunities"?

**Comment by avalot** [comment]
Okay, yes, the final name is **Timeline**.

**Comment by avalot** [comment]
Everything about a contact's interaction with the tenant appears chronologically in the timeline.
Messages exchanged. 
Conversations, calls, transcripts.
Notes about.
Activities performed on the contact (adding fields, changing data)
Future activities planned (todos, meetings) and suggested.

**Comment by avalot** [comment]
We don’t have data for created opportunities yet. That will come later.

**Comment by edifirut** [comment]
for now we are listing what we have: conversations, notes and page views. as we are going to enhance the system with other data, we are going to create specific tasks for that to enhance the timeline
