### ISSUE TITLE
Basic search across some data fields

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-contacts#210]
Search bar that allows me to search across all data fields on a record.

**Comment by avalot** [comment]
First version of the search should be _simple filtering of the homepage list_. That happens only on likely data fields, not all data fields.
Fields that matter for search:

High-priority matches: 
1. Org name
2. Contact last name
3. Email address

Second-priority matches:
4. Contact first name
5. Org website / domain
6. City
7. State
8. Country
