### ISSUE TITLE
Branded & styled login page

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-contacts#213]
Branded and styled login page hosted at app.openline.ai/login

- Ability to SSO w/ google if you have an account
- No ability to create an account (yet)
- If no account, CTA to join waitlist
- Build our own waitlist form that calls customerOS

**Comment by jontyk** [comment]
Completed waitlist. Login linked to Ory outstanding.

**Comment by edifirut** [comment]
implemented
