### ISSUE TITLE
Fail to save when editing an email field

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-contacts#214]
When editing an email address, saving fails

**How to reproduce**
Go to a contact
1. Click the edit button next to their email address
2. Change the email address, or
3. Change the type of email, or
4. Change the "primary" status
5. Try to save the change
6. 

**Expected behavior**
The change would be successful and persisted

**Screenshots**
![Untitled 2](https://user-images.githubusercontent.com/831133/213570167-37a0943e-dc38-4507-93c4-050338e95003.png)

**Additional context**

Thank you for your bug report!  We ❤️ squashing 🪲

**Comment by Kasia9090** [comment]
@avalot is this issue still present on your side? I tested on prod env and was not able to reproduce the issue

**Comment by Kasia9090** [comment]
Issue is no longer reproducible
