### ISSUE TITLE
Website URLs under organization view should be hyperlinks

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-contacts#238]
Website URLs & email addresses should be hyperlinks

**Comment by Kasia9090** [comment]
<img width="235" alt="Screenshot 2023-01-27 at 14 38 57" src="https://user-images.githubusercontent.com/121807793/215100367-b3d51cbb-a213-4695-a1ec-23633c5d628c.png">

Closing because the issue not longer exists (current state can be seen on screenshot above)
