### ISSUE TITLE
If I enter a label against a contact, it doesn't save

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-contacts#239]
![Screenshot 2023-01-26 at 14 42 20](https://user-images.githubusercontent.com/113338429/214864901-ed51bbf6-693c-4616-b1a0-8e8649ddddbb.png)

When I click save and re-open the window to edit, the label is gone

![Screenshot 2023-01-26 at 14 42 54](https://user-images.githubusercontent.com/113338429/214865071-bac1db90-66a1-4d4a-8f76-4a63d0ddbca4.png)

**Comment by mattbr0wn** [comment]
Also looks like it doesn't save the Owner either

**Comment by mattbr0wn** [comment]
Or Type

**Comment by Kasia9090** [comment]
@mattbr0wn can you check what error do you get in the network?

**Comment by mattbr0wn** [comment]
![Screenshot 2023-01-26 at 15 38 20](https://user-images.githubusercontent.com/113338429/214879603-cc5ac497-4a8d-48cd-a436-f9e86513aa94.png)

![Screenshot 2023-01-26 at 15 38 50](https://user-images.githubusercontent.com/113338429/214879640-d4900b56-7f70-46fb-b194-a119d443cbeb.png)
