### ISSUE TITLE
Can't change contact type

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-contacts#240]
For example, on this contact I want to set type to "Vendor"

Ideally, when I click on the type field it shows me the types that have already been created against my account.  I can then either pick a type, or create a new one.

Type tags should also be multi-select as I can have a contact who is a vendor and customer.

![Screenshot 2023-01-26 at 14 45 51](https://user-images.githubusercontent.com/113338429/214866280-baa124d5-8034-4b6b-a2ec-32825906633d.png)

**Comment by edifirut** [comment]
We need to decouple the entity definition with custom fields from this dropdown. The custom fields will remain hidden for now. The contact type dropdown should not be readonly
