### ISSUE TITLE
Contact saves not working

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-contacts#241]
Can't save data against a contact (see screenshot)

![Screenshot 2023-01-26 at 14 49 44](https://user-images.githubusercontent.com/113338429/214866951-74b5721a-b798-4c72-8a33-13fa9d8f9297.png)

**Comment by Kasia9090** [comment]
@mattbr0wn can you check the error code in network?

**Comment by mattbr0wn** [comment]
![Screenshot 2023-01-26 at 15 38 20](https://user-images.githubusercontent.com/113338429/214880590-7873e249-15e2-439f-b275-9419fedb1916.png)

**Comment by Kasia9090** [comment]
fixed in #239
