### ISSUE TITLE
Ability to log notes in Organization view

### ISSUE THREAD

**Issue by mattbr0wn** [openline-ai/openline-contacts#252]
Like in Contacts view, I'd like the ability to log notes against an Organization as well...

**Comment by edifirut** [comment]
@Kasia9090 we already have the mutations that allow us to control the notes for organizations

`    note_CreateForContact(contactId : ID!, input: NoteInput!): Note!
    note_CreateForOrganization(organizationId : ID!, input: NoteInput!): Note!
    note_Update(input: NoteUpdateInput!): Note!
    note_Delete(id: ID!): Result!`
