### ISSUE TITLE
Dashboard tables should be merged on FE

### ISSUE THREAD

**Issue by Kasia9090** [openline-ai/openline-contacts#311]
1. Structure of new table columns:
Contact Full name, [+Contact email]
Contact Role, [+Location name]
Location City, [+State/Country] (only contact location data)
Org Name
Org Industry

**Comment by avalot** [comment]
Columns should be: 
Note: First datum is major one, the one that sorting operates on. [+Second datum is the minor one, can be displayed on the line below]

- Contact Full name, [+Contact email]
- Contact Role, [+Location name]
- Location City, [+State/Country]
- Org Name
- Org Industry

**Comment by Kasia9090** [comment]
cc. @avalot 
1. "Contact Full name, [+Contact email]" - in case organisation has more than one contact should all of them be visible?
2. How should we present contacts that don't belong to any organisation
3. Location of both organisation and contact(s), how should they be presented if there are multiple addresses for multiple contacts in single organisation so it's clear what address(es) belong to which contact?

**Comment by Kasia9090** [comment]
@avalot @Kasia9090
moving it to top of priorities list as it is prerequisite to [search across some data fields](https://github.com/openline-ai/openline-contacts/issues/210)

**Comment by Kasia9090** [comment]
Table is from contact perspective, we show location data only for contact

**Comment by avalot** [comment]
Update: 

![image](https://user-images.githubusercontent.com/831133/216943096-e36b9c13-4ae9-4f54-8b70-ab199f382821.png)
