### ISSUE TITLE
Finalise MVP read only

### ISSUE THREAD

**Issue by jontyk** [openline-ai/openline-contacts#346]
- **Main page** (Finder)
- Search by:
  - [x] City
  - [x] State
  - [x] Email (less urgent)
- [x] Top bar containing larger search box (different background color, search box takes full vertical space)
- [x] Add title to the table: All Contacts
- [x] Top bar with search, table title, header row, footer row, should all be fixed (non-scrolling). In other words, only the table contents should scroll **when scrolling the page**.
- [ ]  Sort order should be indicated
- [x]  Email field (entire TD) should be clickable to the detail view (with cursor) but text should remain unformatted
- [x]  Text should be top-aligned on all rows including heading row.
- [x] Items on first/second line without other line present in contact row should display in correct place even if other line is empty
- [x]  Alternate row background with slightly darker row, to replace the line border between rows.
- [x]   Fixed width of columns and fixed minimal row height (i.e. all rows should behave as if both lines are filled) (for rows with more than 2 lines, which is rare, it's okay if they're a bit taller)
- Sidebar:
- [x]  Dark background colour, and drop shadow, in collapsed as well as open state.
- [x]  Opens by sliding **above** the rest of the page, not by "pushing" it and changing its layout.
- [x]  Mouse pointer on hover
- [x]  Replace User: email with `Hi, {firstName}` or `Hi there!` if no firstName available
- [x]   Make settings a button (align left when menu is open)
- [x]   Make logout a button (align left when menu is open)
 
- [ ] Check contacts that are inaccessible from main list
![image](https://user-images.githubusercontent.com/81759836/217787115-238fd70d-c8bb-4cc6-8317-c4115b4a9009.png)

- **Contacts view**
- [x] Tighten layout, so that more of the timeline history is visible without scrolling.
- [x] Remove "Timeline" heading
- [x] Remove "Now" part of Timeline (not useful yet)
- [x]  Put timestamp immediately above the event (no line between the timestamp and the event)
- [x] Add some whitespace to the bottom of timeline
- [x] Add a "contact created {timestamp}" event to bottom of timeline. If we know who/what created the contact, add "by {creator}"
- [x] In the ID section, show job roles and organizations ( instead of the buttons for coms )
- [x] Remove "Create Note" heading
- [x] "Add Note" button should be inside (floating above) the Add Note box
- [x] Change "Communication" heading to "Details"
- [x] Make sure the edit and delete icons are vertically aligned to the detail.
- [x] Buttons in the ID card should be commented out (not active yet)
- [x] move the "+ add" button BELOW the existing details."
- **Organization view**
- [x] Tighten layout
- [x] Similar changes to above if relevant to unify
- [x] Show contact job roles and organizations
- [x]  Change font of org description to be less prevalent (font currently too heavy and dark)
- [x] Put tags next to name of contacts, not below (reduce number of lines per contact)
- [x] Affordance: Hover background color on whole contact on mouseover (make it look like a clickable item on hover)
- [x] Show the location of the org in "Details"
- [ ] Solve for these errors https://spaces.openline.ai/contact/b426e6bf-1852-46f2-b7b4-ebbb520066c0
- [x] Notably the "HERE" toast

**Comment by avalot** [comment]
Added a few clarifications. Thanks Jonny!

@edifirut please DO ping me when you're doing some of the look & feel bits. We'll iterate faster on CSS together than async on slack. :)

**Comment by jontyk** [comment]
@edifirut sidebar menu seems to have introduced a hover cursor when menu is closed, it also overlaps the chat widget button making it unclickable on the left side

**Comment by edifirut** [comment]
most of the things have been fixed as above. closing this for now
